In [15]:
#18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
 #     50 และปริ้นออกมา
import numpy as np

x = np.random.randint(10,100,(5,5))
print(x)
for i in x:
    for j in i:
        if j > 50 :
            print(j)

[[36 45 17 23 98]
 [33 21 11 55 20]
 [11 83 18 34 29]
 [54 18 65 25 43]
 [88 11 28 91 20]]
98
55
83
54
65
88
91
