In [3]:
# เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
#    3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)
import numpy as np

lst = []
while (len(lst) <= 9):
        x = int(input('ป้อนตัวเลข 10-100 :  '))
        if (x >=10 and x <= 100) and (x not in lst):
            lst.append(x)
            if len(lst) == 9: break
        elif (x <10 or x > 100) or (x  in lst):
            print('กรุณาป้อนใหม่')
print(lst)



ป้อนตัวเลข 10-100 :  10
ป้อนตัวเลข 10-100 :  20
ป้อนตัวเลข 10-100 :  30
ป้อนตัวเลข 10-100 :  40
ป้อนตัวเลข 10-100 :  50
ป้อนตัวเลข 10-100 :  60
ป้อนตัวเลข 10-100 :  70
ป้อนตัวเลข 10-100 :  80
ป้อนตัวเลข 10-100 :  90
[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [15]:
arr = np.array(lst)
arr2 = arr.reshape(3,3)
print(arr2)
arr3 = arr2.T
print(arr3)
print(arr3[2,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
90
