In [3]:
#จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose  
import numpy as np

T = np.random.randint(50,100,(4,4))
print(T.T)

[[98 62 73 94]
 [89 78 77 63]
 [95 95 72 68]
 [63 79 86 80]]
