In [7]:
#17.จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา
#ผมเริ่มด้วยข้อ17ก่อนนะครับ เพื่อให้ข้ออื่นๆสามารถทำต่อได้
import numpy as np

x = np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
#13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

x[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [19]:
#14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

x[3,2:]

array([18, 19, 20])

In [29]:
#15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

x[3:5,0:2]

array([[16, 17],
       [21, 22]])

In [31]:
#16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

x[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])