In [1]:
#จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      #มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา
import numpy as np

x = np.random.randint(10,100,(5,5))
print(x)
lst = []
for i in x:
    for j in i:
        if j > 40 :
              lst.append(j)  
print(lst)


[[11 95 19 95 53]
 [66 96 76 46 20]
 [53 30 14 35 34]
 [62 71 18 74 14]
 [71 38 30 25 84]]
[95, 95, 53, 66, 96, 76, 46, 53, 62, 71, 74, 71, 84]
